openapi: 3.0.0
info:
  version: 0.1.0-SNAPSHOT
  title: Euler API
  description: HTTP API for the Euler File Processing API.
  license:
    name: GNU Lesser General Public License v3.0
    url: https://www.gnu.org/licenses/lgpl-3.0.en.html
components:
  schemas:
    SortBy:
      type: string
      default: CREATION-DATE
      enum:
        - CREATION-DATE
        - ENQUEUED-DATE
        - START-DATE
        - END-DATE
    SortDirection:
      type: string
      default: ASC
      enum:
        - ASC
        - DESC
    JobStatus:
      type: string
      enum:
        - NEW
        - ENQUEUED
        - RUNNING
        - ERROR
        - CANCELLED
        - FINISHED
    Job:
      type: object
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/JobStatus'
        creation-date:
          type: string
          format: date-time
        enqueued-date:
          type: string
          format: date-time
        start-date:
          type: string
          format: date-time
        end-date:
          type: string
          format: date-time
    JobList:
      type: object
      properties:
        total:
          type: integer
        jobs:
          type: array
          items:
            $ref: '#/components/schemas/Job'
    JobStatistics:
      type: object
      properties:
        items-found:
          type: integer
        items-processed:
          type: integer
        timestamp:
          type: string
          format: date-time
    JobConfig:
      type: object
      properties:
        config:
          title: The job json configuration.
          type: object
        seed:
          title: The job seed uri.
          type: string
      required:
        - config
        - seed
    JobDetails:
      allOf:
        - $ref: '#/components/schemas/Job'
        - $ref: '#/components/schemas/JobConfig'
      
paths:
  /jobs:
    get:
      summary: Get a list of jobs.
      operationId: list-jobs
      parameters:
        - name: page
          in: query
          required: false
          description: The page number.
          schema:
            default: 0
            type: integer
        - name: size
          in: query
          required: false
          description: The page size.
          schema:
            default: 10
            maximum: 1000
            type: integer
        - name: sort-by
          in: query
          required: false
          description: The field to sort by.
          schema:
            $ref: '#/components/schemas/SortBy'
        - name: sort-direction
          in: query
          required: false
          description: The direction of the sorting.
          schema:
            $ref: '#/components/schemas/SortDirection'
        - name: status
          in: query
          required: false
          description: The status to be used as filter.
          schema:
            $ref: '#/components/schemas/JobStatus'
      responses:
        '200':
          description: A JSON array of jobs.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobList'
  /job:
    put:
      summary: Create a new job.
      operationId: create-new-job
      requestBody:
        description: The JSON describing the job.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobConfig'
      responses:
        '200':
          description: A JSON of the new job.
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Job'
        '400':
          description: Error creating the job.
  '/job/{job-id}':
    get:
      summary: Get the details of the job.
      operationId: get-jobs-details
      parameters:
        - name: job-id
          in: path
          required: true
          description: The job id.
          schema:
            type: string
      responses:
        '200':
          description: A JSON of the job details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDetails'
        '404':
          description: Job not found
    post:
      summary: Enqueue a new job for execution
      operationId: enqueue-job
      parameters:
        - name: job-id
          in: path
          required: true
          description: The job id.
          schema:
            type: string
      responses:
        '200':
          description: HTTP status code of the current operation.
        '400':
          description: When the job can't be enqueued for execution.
        '404':
          description: Job not found
    delete:
      summary: Cancel the job execution.
      operationId: cancel-job
      parameters:
        - name: job-id
          in: path
          required: true
          description: The job id.
          schema:
            type: string
      responses:
        '200':
          description: HTTP status code of the current operation.
        '400':
          description: When the job can't be cancelled.
        '404':
          description: Job not found

  '/statistics/{job-id}':
    get:
      summary: Get a list of statistics about the job.
      operationId: get-jobs-statistics
      parameters:
        - name: job-id
          in: path
          required: true
          description: The job id.
          schema:
            type: string
      responses:
        '200':
          description: A JSON of the job details.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobStatistics'
        '404':
          description: Job not found
