version: '3.7'
services:
 elasticsearch-euler-http-api:
  build:
   context: .
   dockerfile: Dockerfile-dev
  working_dir: /src
  volumes:
   - .:/src
   - ~/.m2/repository:/mvn/.m2/repository
  user: ${CURRENT_UID}:${CURRENT_GID}
  environment:
   - LANG=C.UTF-8
   - LC_ALL=C.UTF-8
  ports:
   - 8080:8080
   - 8000:8000
  depends_on:
   - elastic-dev
  command: mvn clean spring-boot:run -Dmaven.repo.local=/mvn/.m2/repository -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8000 -Dconfig.file=/src/docker/dev.conf"
 elastic-dev:
  image: amazon/opendistro-for-elasticsearch:1.3.0
  environment:
   discovery.type: single-node
  ports:
   - 9200:9200
   - 9600:9600
  volumes:
   - es-data:/usr/share/elasticsearch/data
   - /src/docker/opendistro-config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml:ro
   - /src/docker/opendistro-internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml:ro
   - /src/docker/opendistro-roles.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml:ro
   - /src/docker/opendistro-roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml:ro
   - /src/docker/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
   - /src/docker/dev-certificates/euler.pem:/usr/share/elasticsearch/config/euler.pem:ro
   - /src/docker/dev-certificates/euler-key.pem:/usr/share/elasticsearch/config/euler-key.pem:ro
   - /src/docker/dev-certificates/node.pem:/usr/share/elasticsearch/config/node.pem:ro
   - /src/docker/dev-certificates/node-key.pem:/usr/share/elasticsearch/config//node-key.pem:ro
   - /src/docker/dev-certificates/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem:ro

volumes:
 es-data:
