version: '3.7'
services:
 elasticsearch-euler-http-api:
  build:
   context: .
   dockerfile: Dockerfile-dev
  working_dir: /src
  volumes:
   - .:/src
  user: ${CURRENT_UID}:${CURRENT_GID}
  ports:
   - 8080:8080
   - 8000:8000
  depends_on:
   - elastic-dev
  command: mvn -Dmaven.repo.local=/mvn/.m2/repository spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8000
 elastic-dev:
  image: amazon/opendistro-for-elasticsearch:1.3.0
  environment:
   discovery.type: single-node
  ports:
   - 9200:9200
   - 9600:9600
  volumes:
   - es-data:/usr/share/elasticsearch/data

volumes:
 es-data: